name: Documentacion Doxygen

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: sudo apt-get install -y doxygen graphviz texlive-latex-recommended texlive-fonts-recommended

      - name: Generar documentacion
        run: doxygen Doxyfile

      - name: Compilar PDF
        run: |
          cd docs/latex
          make pdf
          cp refman.pdf ../html/documentacion.pdf

      - name: Publicar en GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/html

      - name: Deploy
        uses: actions/deploy-pages@v4
